/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProRouteImport } from './routes/pro'
import { Route as PatientRouteImport } from './routes/patient'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AssessmentIndexRouteImport } from './routes/assessment.index'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as RoadmapIdRouteImport } from './routes/roadmap.$id'
import { Route as ProTreatmentPlansRouteImport } from './routes/pro.treatment-plans'
import { Route as ProTemplatesRouteImport } from './routes/pro.templates'
import { Route as ProTeamRouteImport } from './routes/pro.team'
import { Route as ProTasksRouteImport } from './routes/pro.tasks'
import { Route as ProSettingsRouteImport } from './routes/pro.settings'
import { Route as ProQuotesRouteImport } from './routes/pro.quotes'
import { Route as ProPatientsRouteImport } from './routes/pro.patients'
import { Route as ProLeadsRouteImport } from './routes/pro.leads'
import { Route as ProDashboardRouteImport } from './routes/pro.dashboard'
import { Route as ProBrandingRouteImport } from './routes/pro.branding'
import { Route as ProAppointmentsRouteImport } from './routes/pro.appointments'
import { Route as PatientSplatRouteImport } from './routes/patient.$'
import { Route as ConfirmationIdRouteImport } from './routes/confirmation.$id'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminClinicsRouteImport } from './routes/admin.clinics'
import { Route as PublicTreatmentsRouteImport } from './routes/_public.treatments'
import { Route as PublicStartRouteImport } from './routes/_public.start'
import { Route as PublicRegisterRouteImport } from './routes/_public.register'
import { Route as PublicLoginRouteImport } from './routes/_public.login'
import { Route as PublicHowItWorksRouteImport } from './routes/_public.how-it-works'
import { Route as PublicForClinicsRouteImport } from './routes/_public.for-clinics'
import { Route as PublicDestinationsRouteImport } from './routes/_public.destinations'
import { Route as PublicClinicsRouteImport } from './routes/_public.clinics'
import { Route as PublicAboutRouteImport } from './routes/_public.about'
import { Route as SharedTreatmentPlanTokenRouteImport } from './routes/shared.treatment-plan.$token'
import { Route as ProTreatmentPlansIdRouteImport } from './routes/pro.treatment-plans.$id'
import { Route as ProQuotesIdRouteImport } from './routes/pro.quotes.$id'
import { Route as ProPatientsIdRouteImport } from './routes/pro.patients.$id'
import { Route as PublicClinicsSlugRouteImport } from './routes/_public.clinics.$slug'

const ProRoute = ProRouteImport.update({
  id: '/pro',
  path: '/pro',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientRoute = PatientRouteImport.update({
  id: '/patient',
  path: '/patient',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AssessmentIndexRoute = AssessmentIndexRouteImport.update({
  id: '/assessment/',
  path: '/assessment/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const RoadmapIdRoute = RoadmapIdRouteImport.update({
  id: '/roadmap/$id',
  path: '/roadmap/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProTreatmentPlansRoute = ProTreatmentPlansRouteImport.update({
  id: '/treatment-plans',
  path: '/treatment-plans',
  getParentRoute: () => ProRoute,
} as any)
const ProTemplatesRoute = ProTemplatesRouteImport.update({
  id: '/templates',
  path: '/templates',
  getParentRoute: () => ProRoute,
} as any)
const ProTeamRoute = ProTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => ProRoute,
} as any)
const ProTasksRoute = ProTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => ProRoute,
} as any)
const ProSettingsRoute = ProSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ProRoute,
} as any)
const ProQuotesRoute = ProQuotesRouteImport.update({
  id: '/quotes',
  path: '/quotes',
  getParentRoute: () => ProRoute,
} as any)
const ProPatientsRoute = ProPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => ProRoute,
} as any)
const ProLeadsRoute = ProLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => ProRoute,
} as any)
const ProDashboardRoute = ProDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProRoute,
} as any)
const ProBrandingRoute = ProBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => ProRoute,
} as any)
const ProAppointmentsRoute = ProAppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => ProRoute,
} as any)
const PatientSplatRoute = PatientSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => PatientRoute,
} as any)
const ConfirmationIdRoute = ConfirmationIdRouteImport.update({
  id: '/confirmation/$id',
  path: '/confirmation/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClinicsRoute = AdminClinicsRouteImport.update({
  id: '/clinics',
  path: '/clinics',
  getParentRoute: () => AdminRoute,
} as any)
const PublicTreatmentsRoute = PublicTreatmentsRouteImport.update({
  id: '/treatments',
  path: '/treatments',
  getParentRoute: () => PublicRoute,
} as any)
const PublicStartRoute = PublicStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicHowItWorksRoute = PublicHowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => PublicRoute,
} as any)
const PublicForClinicsRoute = PublicForClinicsRouteImport.update({
  id: '/for-clinics',
  path: '/for-clinics',
  getParentRoute: () => PublicRoute,
} as any)
const PublicDestinationsRoute = PublicDestinationsRouteImport.update({
  id: '/destinations',
  path: '/destinations',
  getParentRoute: () => PublicRoute,
} as any)
const PublicClinicsRoute = PublicClinicsRouteImport.update({
  id: '/clinics',
  path: '/clinics',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const SharedTreatmentPlanTokenRoute =
  SharedTreatmentPlanTokenRouteImport.update({
    id: '/shared/treatment-plan/$token',
    path: '/shared/treatment-plan/$token',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProTreatmentPlansIdRoute = ProTreatmentPlansIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProTreatmentPlansRoute,
} as any)
const ProQuotesIdRoute = ProQuotesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProQuotesRoute,
} as any)
const ProPatientsIdRoute = ProPatientsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ProPatientsRoute,
} as any)
const PublicClinicsSlugRoute = PublicClinicsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PublicClinicsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/patient': typeof PatientRouteWithChildren
  '/pro': typeof ProRouteWithChildren
  '/about': typeof PublicAboutRoute
  '/clinics': typeof PublicClinicsRouteWithChildren
  '/destinations': typeof PublicDestinationsRoute
  '/for-clinics': typeof PublicForClinicsRoute
  '/how-it-works': typeof PublicHowItWorksRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/start': typeof PublicStartRoute
  '/treatments': typeof PublicTreatmentsRoute
  '/admin/clinics': typeof AdminClinicsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/confirmation/$id': typeof ConfirmationIdRoute
  '/patient/$': typeof PatientSplatRoute
  '/pro/appointments': typeof ProAppointmentsRoute
  '/pro/branding': typeof ProBrandingRoute
  '/pro/dashboard': typeof ProDashboardRoute
  '/pro/leads': typeof ProLeadsRoute
  '/pro/patients': typeof ProPatientsRouteWithChildren
  '/pro/quotes': typeof ProQuotesRouteWithChildren
  '/pro/settings': typeof ProSettingsRoute
  '/pro/tasks': typeof ProTasksRoute
  '/pro/team': typeof ProTeamRoute
  '/pro/templates': typeof ProTemplatesRoute
  '/pro/treatment-plans': typeof ProTreatmentPlansRouteWithChildren
  '/roadmap/$id': typeof RoadmapIdRoute
  '/assessment/': typeof AssessmentIndexRoute
  '/clinics/$slug': typeof PublicClinicsSlugRoute
  '/pro/patients/$id': typeof ProPatientsIdRoute
  '/pro/quotes/$id': typeof ProQuotesIdRoute
  '/pro/treatment-plans/$id': typeof ProTreatmentPlansIdRoute
  '/shared/treatment-plan/$token': typeof SharedTreatmentPlanTokenRoute
}
export interface FileRoutesByTo {
  '/admin': typeof AdminRouteWithChildren
  '/patient': typeof PatientRouteWithChildren
  '/pro': typeof ProRouteWithChildren
  '/about': typeof PublicAboutRoute
  '/clinics': typeof PublicClinicsRouteWithChildren
  '/destinations': typeof PublicDestinationsRoute
  '/for-clinics': typeof PublicForClinicsRoute
  '/how-it-works': typeof PublicHowItWorksRoute
  '/login': typeof PublicLoginRoute
  '/register': typeof PublicRegisterRoute
  '/start': typeof PublicStartRoute
  '/treatments': typeof PublicTreatmentsRoute
  '/admin/clinics': typeof AdminClinicsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/confirmation/$id': typeof ConfirmationIdRoute
  '/patient/$': typeof PatientSplatRoute
  '/pro/appointments': typeof ProAppointmentsRoute
  '/pro/branding': typeof ProBrandingRoute
  '/pro/dashboard': typeof ProDashboardRoute
  '/pro/leads': typeof ProLeadsRoute
  '/pro/patients': typeof ProPatientsRouteWithChildren
  '/pro/quotes': typeof ProQuotesRouteWithChildren
  '/pro/settings': typeof ProSettingsRoute
  '/pro/tasks': typeof ProTasksRoute
  '/pro/team': typeof ProTeamRoute
  '/pro/templates': typeof ProTemplatesRoute
  '/pro/treatment-plans': typeof ProTreatmentPlansRouteWithChildren
  '/roadmap/$id': typeof RoadmapIdRoute
  '/': typeof PublicIndexRoute
  '/assessment': typeof AssessmentIndexRoute
  '/clinics/$slug': typeof PublicClinicsSlugRoute
  '/pro/patients/$id': typeof ProPatientsIdRoute
  '/pro/quotes/$id': typeof ProQuotesIdRoute
  '/pro/treatment-plans/$id': typeof ProTreatmentPlansIdRoute
  '/shared/treatment-plan/$token': typeof SharedTreatmentPlanTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/patient': typeof PatientRouteWithChildren
  '/pro': typeof ProRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/clinics': typeof PublicClinicsRouteWithChildren
  '/_public/destinations': typeof PublicDestinationsRoute
  '/_public/for-clinics': typeof PublicForClinicsRoute
  '/_public/how-it-works': typeof PublicHowItWorksRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_public/start': typeof PublicStartRoute
  '/_public/treatments': typeof PublicTreatmentsRoute
  '/admin/clinics': typeof AdminClinicsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/confirmation/$id': typeof ConfirmationIdRoute
  '/patient/$': typeof PatientSplatRoute
  '/pro/appointments': typeof ProAppointmentsRoute
  '/pro/branding': typeof ProBrandingRoute
  '/pro/dashboard': typeof ProDashboardRoute
  '/pro/leads': typeof ProLeadsRoute
  '/pro/patients': typeof ProPatientsRouteWithChildren
  '/pro/quotes': typeof ProQuotesRouteWithChildren
  '/pro/settings': typeof ProSettingsRoute
  '/pro/tasks': typeof ProTasksRoute
  '/pro/team': typeof ProTeamRoute
  '/pro/templates': typeof ProTemplatesRoute
  '/pro/treatment-plans': typeof ProTreatmentPlansRouteWithChildren
  '/roadmap/$id': typeof RoadmapIdRoute
  '/_public/': typeof PublicIndexRoute
  '/assessment/': typeof AssessmentIndexRoute
  '/_public/clinics/$slug': typeof PublicClinicsSlugRoute
  '/pro/patients/$id': typeof ProPatientsIdRoute
  '/pro/quotes/$id': typeof ProQuotesIdRoute
  '/pro/treatment-plans/$id': typeof ProTreatmentPlansIdRoute
  '/shared/treatment-plan/$token': typeof SharedTreatmentPlanTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/patient'
    | '/pro'
    | '/about'
    | '/clinics'
    | '/destinations'
    | '/for-clinics'
    | '/how-it-works'
    | '/login'
    | '/register'
    | '/start'
    | '/treatments'
    | '/admin/clinics'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/admin/users'
    | '/confirmation/$id'
    | '/patient/$'
    | '/pro/appointments'
    | '/pro/branding'
    | '/pro/dashboard'
    | '/pro/leads'
    | '/pro/patients'
    | '/pro/quotes'
    | '/pro/settings'
    | '/pro/tasks'
    | '/pro/team'
    | '/pro/templates'
    | '/pro/treatment-plans'
    | '/roadmap/$id'
    | '/assessment/'
    | '/clinics/$slug'
    | '/pro/patients/$id'
    | '/pro/quotes/$id'
    | '/pro/treatment-plans/$id'
    | '/shared/treatment-plan/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/admin'
    | '/patient'
    | '/pro'
    | '/about'
    | '/clinics'
    | '/destinations'
    | '/for-clinics'
    | '/how-it-works'
    | '/login'
    | '/register'
    | '/start'
    | '/treatments'
    | '/admin/clinics'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/admin/users'
    | '/confirmation/$id'
    | '/patient/$'
    | '/pro/appointments'
    | '/pro/branding'
    | '/pro/dashboard'
    | '/pro/leads'
    | '/pro/patients'
    | '/pro/quotes'
    | '/pro/settings'
    | '/pro/tasks'
    | '/pro/team'
    | '/pro/templates'
    | '/pro/treatment-plans'
    | '/roadmap/$id'
    | '/'
    | '/assessment'
    | '/clinics/$slug'
    | '/pro/patients/$id'
    | '/pro/quotes/$id'
    | '/pro/treatment-plans/$id'
    | '/shared/treatment-plan/$token'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/patient'
    | '/pro'
    | '/_public/about'
    | '/_public/clinics'
    | '/_public/destinations'
    | '/_public/for-clinics'
    | '/_public/how-it-works'
    | '/_public/login'
    | '/_public/register'
    | '/_public/start'
    | '/_public/treatments'
    | '/admin/clinics'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/admin/users'
    | '/confirmation/$id'
    | '/patient/$'
    | '/pro/appointments'
    | '/pro/branding'
    | '/pro/dashboard'
    | '/pro/leads'
    | '/pro/patients'
    | '/pro/quotes'
    | '/pro/settings'
    | '/pro/tasks'
    | '/pro/team'
    | '/pro/templates'
    | '/pro/treatment-plans'
    | '/roadmap/$id'
    | '/_public/'
    | '/assessment/'
    | '/_public/clinics/$slug'
    | '/pro/patients/$id'
    | '/pro/quotes/$id'
    | '/pro/treatment-plans/$id'
    | '/shared/treatment-plan/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  PatientRoute: typeof PatientRouteWithChildren
  ProRoute: typeof ProRouteWithChildren
  ConfirmationIdRoute: typeof ConfirmationIdRoute
  RoadmapIdRoute: typeof RoadmapIdRoute
  AssessmentIndexRoute: typeof AssessmentIndexRoute
  SharedTreatmentPlanTokenRoute: typeof SharedTreatmentPlanTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pro': {
      id: '/pro'
      path: '/pro'
      fullPath: '/pro'
      preLoaderRoute: typeof ProRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient': {
      id: '/patient'
      path: '/patient'
      fullPath: '/patient'
      preLoaderRoute: typeof PatientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assessment/': {
      id: '/assessment/'
      path: '/assessment'
      fullPath: '/assessment/'
      preLoaderRoute: typeof AssessmentIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/roadmap/$id': {
      id: '/roadmap/$id'
      path: '/roadmap/$id'
      fullPath: '/roadmap/$id'
      preLoaderRoute: typeof RoadmapIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/treatment-plans': {
      id: '/pro/treatment-plans'
      path: '/treatment-plans'
      fullPath: '/pro/treatment-plans'
      preLoaderRoute: typeof ProTreatmentPlansRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/templates': {
      id: '/pro/templates'
      path: '/templates'
      fullPath: '/pro/templates'
      preLoaderRoute: typeof ProTemplatesRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/team': {
      id: '/pro/team'
      path: '/team'
      fullPath: '/pro/team'
      preLoaderRoute: typeof ProTeamRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/tasks': {
      id: '/pro/tasks'
      path: '/tasks'
      fullPath: '/pro/tasks'
      preLoaderRoute: typeof ProTasksRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/settings': {
      id: '/pro/settings'
      path: '/settings'
      fullPath: '/pro/settings'
      preLoaderRoute: typeof ProSettingsRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/quotes': {
      id: '/pro/quotes'
      path: '/quotes'
      fullPath: '/pro/quotes'
      preLoaderRoute: typeof ProQuotesRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/patients': {
      id: '/pro/patients'
      path: '/patients'
      fullPath: '/pro/patients'
      preLoaderRoute: typeof ProPatientsRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/leads': {
      id: '/pro/leads'
      path: '/leads'
      fullPath: '/pro/leads'
      preLoaderRoute: typeof ProLeadsRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/dashboard': {
      id: '/pro/dashboard'
      path: '/dashboard'
      fullPath: '/pro/dashboard'
      preLoaderRoute: typeof ProDashboardRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/branding': {
      id: '/pro/branding'
      path: '/branding'
      fullPath: '/pro/branding'
      preLoaderRoute: typeof ProBrandingRouteImport
      parentRoute: typeof ProRoute
    }
    '/pro/appointments': {
      id: '/pro/appointments'
      path: '/appointments'
      fullPath: '/pro/appointments'
      preLoaderRoute: typeof ProAppointmentsRouteImport
      parentRoute: typeof ProRoute
    }
    '/patient/$': {
      id: '/patient/$'
      path: '/$'
      fullPath: '/patient/$'
      preLoaderRoute: typeof PatientSplatRouteImport
      parentRoute: typeof PatientRoute
    }
    '/confirmation/$id': {
      id: '/confirmation/$id'
      path: '/confirmation/$id'
      fullPath: '/confirmation/$id'
      preLoaderRoute: typeof ConfirmationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clinics': {
      id: '/admin/clinics'
      path: '/clinics'
      fullPath: '/admin/clinics'
      preLoaderRoute: typeof AdminClinicsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/treatments': {
      id: '/_public/treatments'
      path: '/treatments'
      fullPath: '/treatments'
      preLoaderRoute: typeof PublicTreatmentsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/start': {
      id: '/_public/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof PublicStartRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/how-it-works': {
      id: '/_public/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof PublicHowItWorksRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/for-clinics': {
      id: '/_public/for-clinics'
      path: '/for-clinics'
      fullPath: '/for-clinics'
      preLoaderRoute: typeof PublicForClinicsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/destinations': {
      id: '/_public/destinations'
      path: '/destinations'
      fullPath: '/destinations'
      preLoaderRoute: typeof PublicDestinationsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/clinics': {
      id: '/_public/clinics'
      path: '/clinics'
      fullPath: '/clinics'
      preLoaderRoute: typeof PublicClinicsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/shared/treatment-plan/$token': {
      id: '/shared/treatment-plan/$token'
      path: '/shared/treatment-plan/$token'
      fullPath: '/shared/treatment-plan/$token'
      preLoaderRoute: typeof SharedTreatmentPlanTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pro/treatment-plans/$id': {
      id: '/pro/treatment-plans/$id'
      path: '/$id'
      fullPath: '/pro/treatment-plans/$id'
      preLoaderRoute: typeof ProTreatmentPlansIdRouteImport
      parentRoute: typeof ProTreatmentPlansRoute
    }
    '/pro/quotes/$id': {
      id: '/pro/quotes/$id'
      path: '/$id'
      fullPath: '/pro/quotes/$id'
      preLoaderRoute: typeof ProQuotesIdRouteImport
      parentRoute: typeof ProQuotesRoute
    }
    '/pro/patients/$id': {
      id: '/pro/patients/$id'
      path: '/$id'
      fullPath: '/pro/patients/$id'
      preLoaderRoute: typeof ProPatientsIdRouteImport
      parentRoute: typeof ProPatientsRoute
    }
    '/_public/clinics/$slug': {
      id: '/_public/clinics/$slug'
      path: '/$slug'
      fullPath: '/clinics/$slug'
      preLoaderRoute: typeof PublicClinicsSlugRouteImport
      parentRoute: typeof PublicClinicsRoute
    }
  }
}

interface PublicClinicsRouteChildren {
  PublicClinicsSlugRoute: typeof PublicClinicsSlugRoute
}

const PublicClinicsRouteChildren: PublicClinicsRouteChildren = {
  PublicClinicsSlugRoute: PublicClinicsSlugRoute,
}

const PublicClinicsRouteWithChildren = PublicClinicsRoute._addFileChildren(
  PublicClinicsRouteChildren,
)

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicClinicsRoute: typeof PublicClinicsRouteWithChildren
  PublicDestinationsRoute: typeof PublicDestinationsRoute
  PublicForClinicsRoute: typeof PublicForClinicsRoute
  PublicHowItWorksRoute: typeof PublicHowItWorksRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicStartRoute: typeof PublicStartRoute
  PublicTreatmentsRoute: typeof PublicTreatmentsRoute
  PublicIndexRoute: typeof PublicIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicClinicsRoute: PublicClinicsRouteWithChildren,
  PublicDestinationsRoute: PublicDestinationsRoute,
  PublicForClinicsRoute: PublicForClinicsRoute,
  PublicHowItWorksRoute: PublicHowItWorksRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicStartRoute: PublicStartRoute,
  PublicTreatmentsRoute: PublicTreatmentsRoute,
  PublicIndexRoute: PublicIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminRouteChildren {
  AdminClinicsRoute: typeof AdminClinicsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClinicsRoute: AdminClinicsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PatientRouteChildren {
  PatientSplatRoute: typeof PatientSplatRoute
}

const PatientRouteChildren: PatientRouteChildren = {
  PatientSplatRoute: PatientSplatRoute,
}

const PatientRouteWithChildren =
  PatientRoute._addFileChildren(PatientRouteChildren)

interface ProPatientsRouteChildren {
  ProPatientsIdRoute: typeof ProPatientsIdRoute
}

const ProPatientsRouteChildren: ProPatientsRouteChildren = {
  ProPatientsIdRoute: ProPatientsIdRoute,
}

const ProPatientsRouteWithChildren = ProPatientsRoute._addFileChildren(
  ProPatientsRouteChildren,
)

interface ProQuotesRouteChildren {
  ProQuotesIdRoute: typeof ProQuotesIdRoute
}

const ProQuotesRouteChildren: ProQuotesRouteChildren = {
  ProQuotesIdRoute: ProQuotesIdRoute,
}

const ProQuotesRouteWithChildren = ProQuotesRoute._addFileChildren(
  ProQuotesRouteChildren,
)

interface ProTreatmentPlansRouteChildren {
  ProTreatmentPlansIdRoute: typeof ProTreatmentPlansIdRoute
}

const ProTreatmentPlansRouteChildren: ProTreatmentPlansRouteChildren = {
  ProTreatmentPlansIdRoute: ProTreatmentPlansIdRoute,
}

const ProTreatmentPlansRouteWithChildren =
  ProTreatmentPlansRoute._addFileChildren(ProTreatmentPlansRouteChildren)

interface ProRouteChildren {
  ProAppointmentsRoute: typeof ProAppointmentsRoute
  ProBrandingRoute: typeof ProBrandingRoute
  ProDashboardRoute: typeof ProDashboardRoute
  ProLeadsRoute: typeof ProLeadsRoute
  ProPatientsRoute: typeof ProPatientsRouteWithChildren
  ProQuotesRoute: typeof ProQuotesRouteWithChildren
  ProSettingsRoute: typeof ProSettingsRoute
  ProTasksRoute: typeof ProTasksRoute
  ProTeamRoute: typeof ProTeamRoute
  ProTemplatesRoute: typeof ProTemplatesRoute
  ProTreatmentPlansRoute: typeof ProTreatmentPlansRouteWithChildren
}

const ProRouteChildren: ProRouteChildren = {
  ProAppointmentsRoute: ProAppointmentsRoute,
  ProBrandingRoute: ProBrandingRoute,
  ProDashboardRoute: ProDashboardRoute,
  ProLeadsRoute: ProLeadsRoute,
  ProPatientsRoute: ProPatientsRouteWithChildren,
  ProQuotesRoute: ProQuotesRouteWithChildren,
  ProSettingsRoute: ProSettingsRoute,
  ProTasksRoute: ProTasksRoute,
  ProTeamRoute: ProTeamRoute,
  ProTemplatesRoute: ProTemplatesRoute,
  ProTreatmentPlansRoute: ProTreatmentPlansRouteWithChildren,
}

const ProRouteWithChildren = ProRoute._addFileChildren(ProRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  PatientRoute: PatientRouteWithChildren,
  ProRoute: ProRouteWithChildren,
  ConfirmationIdRoute: ConfirmationIdRoute,
  RoadmapIdRoute: RoadmapIdRoute,
  AssessmentIndexRoute: AssessmentIndexRoute,
  SharedTreatmentPlanTokenRoute: SharedTreatmentPlanTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
